//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODEGA_SAC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BODEGA_SACEntities : DbContext
    {
        public BODEGA_SACEntities()
            : base("name=BODEGA_SACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_CATEGORY> TB_CATEGORY { get; set; }
        public virtual DbSet<TB_CUSTOMER> TB_CUSTOMER { get; set; }
        public virtual DbSet<TB_DEBT> TB_DEBT { get; set; }
        public virtual DbSet<TB_DETAIL_SALE> TB_DETAIL_SALE { get; set; }
        public virtual DbSet<TB_EMPLOYEE> TB_EMPLOYEE { get; set; }
        public virtual DbSet<TB_LOGIN_EMPLOYEE> TB_LOGIN_EMPLOYEE { get; set; }
        public virtual DbSet<TB_PRODUCT> TB_PRODUCT { get; set; }
        public virtual DbSet<TB_ROLE_EMPLOYEE> TB_ROLE_EMPLOYEE { get; set; }
        public virtual DbSet<TB_SALE> TB_SALE { get; set; }
    }
}
