//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODEGA_SAC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DEBT
    {
        public int ID_DEBT { get; set; }
        public int ID_SALE { get; set; }
        public int ID_CUSTOMER { get; set; }
        public decimal TOTAL_SALE { get; set; }
        public decimal AMOUNT_PAID_SALE { get; set; }
        public decimal AMOUNT_TO_PAY_SALE { get; set; }
        public int STATUS_DEBT { get; set; }
    
        public virtual TB_CUSTOMER TB_CUSTOMER { get; set; }
        public virtual TB_SALE TB_SALE { get; set; }
    }
}
