//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODEGA_SAC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DETAIL_SALE
    {
        public int ID_SALE { get; set; }
        public int ID_PRODUCT { get; set; }
        public decimal PRICE_PRODUCT_SALE { get; set; }
        public int AMOUNT_PRODUCT_SALE { get; set; }
        public int ID_DETAIL_SALE { get; set; }
    
        public virtual TB_PRODUCT TB_PRODUCT { get; set; }
        public virtual TB_SALE TB_SALE { get; set; }
    }
}
