//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODEGA_SAC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PRODUCT()
        {
            this.TB_DETAIL_SALE = new HashSet<TB_DETAIL_SALE>();
        }
    
        public int ID_PRODUCT { get; set; }
        public int CODE_PRODUCT { get; set; }
        public string NAME_PRODUCT { get; set; }
        public string DESCRIPTION_PRODUCT { get; set; }
        public decimal PRICE_PRODUCT { get; set; }
        public int STOCK_PRODUCT { get; set; }
        public int STATUS_PRODUCT { get; set; }
        public int ID_CATEGORY { get; set; }
    
        public virtual TB_CATEGORY TB_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DETAIL_SALE> TB_DETAIL_SALE { get; set; }
    }
}
