//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODEGA_SAC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SALE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SALE()
        {
            this.TB_DEBT = new HashSet<TB_DEBT>();
            this.TB_DETAIL_SALE = new HashSet<TB_DETAIL_SALE>();
        }
    
        public int ID_SALE { get; set; }
        public int ID_EMPLOYEE { get; set; }
        public int ID_CUSTOMER { get; set; }
        public System.DateTime DATE_SALE { get; set; }
        public decimal TOTAL_SALE { get; set; }
        public int STATUS_SALE { get; set; }
    
        public virtual TB_CUSTOMER TB_CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DEBT> TB_DEBT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DETAIL_SALE> TB_DETAIL_SALE { get; set; }
        public virtual TB_EMPLOYEE TB_EMPLOYEE { get; set; }
    }
}
